version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-usageplan-collector"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p366tg09hglt"
s3_prefix = "api-usageplan-collector"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CloudWatchNameSpace=\"MY_APIS\" ApplicationId=\"CAPI\""
image_repositories = []
