# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  api-usage-plan

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  CloudWatchNameSpace:
    Type: String
    Description: The default Cloud Watch Namespace for Customer CW Metrics
    Default: "CRAPI"
  ApplicationId:
    Type: String
    Description: The Application Specific Cloud Watch Namespace
    Default: "CAPI"

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  UsagePlanLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/api-usage-plan.UsagePlanHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: APIGatewayGetUsageMetrics
              Effect: Allow
              Action:
                - apigateway:GET
              Resource:
                - "arn:aws:apigateway:*::/usageplans/*"
                - "arn:aws:apigateway:*::/usageplans"
                - "arn:aws:apigateway:*::/usageplans/*/keys/*"
                - "arn:aws:apigateway:*::/usageplans/*/keys"
            - Sid: CloudwatchPutMetricData
              Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource:
                - "*"
      Environment:
        Variables:
          CloudWatchNameSpace: !Ref CloudWatchNameSpace
          ApplicationId: !Ref ApplicationId
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: "rate(1 hour)"
            Name: API-UsagePlan-Collector
            Description: "Hourly Trigger to Collect API Gateway UsagePlan Metrics"
            Enabled: true
